### ISSUE TITLE
Conversion error

### ISSUE THREAD

**Issue by ghost** [TUMFTM/sim_battery_system#1]
hello there, as Markus Lienkamp mentioned in https://www.researchgate.net/post/How_can_I_model_a_battery_in_Python_complete_coding

I am not able to convert matlab file to .py using "smop".
I tried this:
```smop main_sim_battery_system.m```
yes, i choose the correct path of that folder
but still I get this error:
```c:\users\username\appdata\local\programs\python\python39\lib\site-packages\ply\lex.py:760: FutureWarning: Possible nested set at position 65                                                                                                         c = re.compile('(?P<%s>%s)' % (fname, _get_regex(f)), self.reflags)                                                   c:\users\username\appdata\local\programs\python\python39\lib\site-packages\ply\lex.py:498: FutureWarning: Possible nested set at position 118                                                                                                        lexre = re.compile(regex, reflags)                                                                                    Traceback (most recent call last):                                                                                        File "c:\users\username\appdata\local\programs\python\python39\lib\site-packages\smop\main.py", line 61, in main             stmt_list = parse.parse(buf if buf[-1] == '\n' else buf + '\n')                                                       File "c:\users\username\appdata\local\programs\python\python39\lib\site-packages\smop\parse.py", line 849, in parse          p = parser.parse(                                                                                                     File "c:\users\username\appdata\local\programs\python\python39\lib\site-packages\ply\yacc.py", line 331, in parse            return self.parseopt(input, lexer, debug, tracking, tokenfunc)                                                        File "c:\users\username\appdata\local\programs\python\python39\lib\site-packages\ply\yacc.py", line 909, in parseopt         tok = call_errorfunc(self.errorfunc, errtoken, self)                                                                  File "c:\users\username\appdata\local\programs\python\python39\lib\site-packages\ply\yacc.py", line 192, in call_errorfunc                                                                                                                           r = errorfunc(token)                                                                                                  File "c:\users\username\appdata\local\programs\python\python39\lib\site-packages\smop\parse.py", line 836, in p_error        raise_exception(SyntaxError,                                                                                          File "c:\users\username\appdata\local\programs\python\python39\lib\site-packages\smop\lexer.py", line 335, in raise_exception                                                                                                                        raise error_type(message, (options.filename,                                                                          File "main_sim_battery_system.m", line 15                                                                                 run parameters/cell_parameters_NCR18650PF_4RC.m             % Load cell parameters                                                     ^                                                                                                  SyntaxError: Unexpected "/" (parser)                                                                                    Errors: 1  ```

**Comment by ghost** [comment]
Waiting for your reply

**Comment by ghost** [comment]
nope no reply
